Feature branch
Amrit131/hello-microverse pull request #1
Opened 2022-09-20 15:39 UTC by Amrit131

Testing Microverse linters.

2022-09-20 16:39 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @Amrit131 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🙌🤗

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Descriptive commit messages ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️

- [x] Kindly update the Pull Request description so that it has a short summary of the changes you made in this PR as described [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 🤗

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 16:39 UTC, awais-amjed commented on README.md
> +=======
Kindly remove these lines and make sure that the Readme resembles the [Microverse Readme Template](https://github.com/microverseinc/readme-template) as closely as possible, and only make the necessary changes 🤗

2022-09-20 16:39 UTC, awais-amjed commented on text.md
> +This file should be ignored by git
Kindly add this file to `.gitignore` following the guidelines in your [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#requirements) 🤗

![image](https://user-images.githubusercontent.com/73714615/191314951-ceda6bbd-e4ee-4c70-8af5-ad34f69df472.png)

2022-09-20 17:29 UTC, Amrit131 commented on README.md
> +=======
I will surely do the changes, Thank you! for the review.

2022-09-20 17:35 UTC, Amrit131 commented
> # STATUS: CHANGES REQUIRED ♻️
> Hi @Amrit131 ,
> 
> Good job so far! 👏👏 There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🙌🤗
> 
> ## Highlights
> * [x]  Descriptive Pull Request ✔️
> * [x]  Descriptive commit messages ✔️
> * [x]  Good code organization ✔️
> 
> ![gif](https://camo.githubusercontent.com/0b6134a224332efd68cb15c3a3ff40ac036be75801f5ab22f0905d6b343c8a60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f714c57644d5958314e594632672f67697068792d646f776e73697a65642d6c617267652e676966) [ ![gif](https://camo.githubusercontent.com/0b6134a224332efd68cb15c3a3ff40ac036be75801f5ab22f0905d6b343c8a60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f714c57644d5958314e594632672f67697068792d646f776e73697a65642d6c617267652e676966) ](https://camo.githubusercontent.com/0b6134a224332efd68cb15c3a3ff40ac036be75801f5ab22f0905d6b343c8a60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f714c57644d5958314e594632672f67697068792d646f776e73697a65642d6c617267652e676966) [ ](https://camo.githubusercontent.com/0b6134a224332efd68cb15c3a3ff40ac036be75801f5ab22f0905d6b343c8a60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f714c57644d5958314e594632672f67697068792d646f776e73697a65642d6c617267652e676966)
> 
> ## Required Changes ♻️
> * [x]  Kindly update the Pull Request description so that it has a short summary of the changes you made in this PR as described [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 🤗
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 17:42 UTC, Amrit131 commented
Sorry for the late reply and replying through email, it's just that it's my
first code review and I am a little bit confused. So I resolved the issue
and clicked on the resolve issue button present in the branch but I don't
know if I need to open another code review request or just wait for you.

Thank you
Amrit

On Tue, Sep 20, 2022 at 10:09 PM Awais Amjed ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: CHANGES REQUIRED ♻️
>
> Hi @Amrit131 <https://github.com/Amrit131> ,
>
> Good job so far! 👏👏
> There are some issues that you still need to work on to go to the next
> project but you are almost there! 🥳🙌🤗
> Highlights
>
>    - Descriptive Pull Request ✔️
>    - Descriptive commit messages ✔️
>    - Good code organization ✔️
>
> [image: gif]
> <https://camo.githubusercontent.com/0b6134a224332efd68cb15c3a3ff40ac036be75801f5ab22f0905d6b343c8a60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f714c57644d5958314e594632672f67697068792d646f776e73697a65642d6c617267652e676966>
> Required Changes ♻️
>
>    - Kindly update the Pull Request description so that it has a short
>    summary of the changes you made in this PR as described here
>    <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md>
>    🤗
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/Amrit131/hello-microverse/pull/1#discussion_r975590792>
> :
>
> > +<<<<<<< HEAD
>
> +# hello-microverse
>
> +This is a repository for my first project in Microverse program...
>
> +=======
>
>
> Kindly remove these lines and make sure that the Readme resembles the Microverse
> Readme Template <https://github.com/microverseinc/readme-template> as
> closely as possible, and only make the necessary changes 🤗
> ------------------------------
>
> In text.md
> <https://github.com/Amrit131/hello-microverse/pull/1#discussion_r975592246>
> :
>
> > @@ -0,0 +1 @@
>
> +This file should be ignored by git
>
>
> Kindly add this file to .gitignore following the guidelines in your project
> requirements
> <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#requirements>
> 🤗
>
> [image: image]
> <https://user-images.githubusercontent.com/73714615/191314951-ceda6bbd-e4ee-4c70-8af5-ad34f69df472.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Amrit131/hello-microverse/pull/1#pullrequestreview-1114152365>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU4JI5AEJDOBDMA4DX2JLULV7HSETANCNFSM6AAAAAAQRGQIFU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-20 17:43 UTC, Amrit131 commented
@awais-amjed So I just read that I need to tag you sorry for all this confusion.

2022-09-20 21:25 UTC, awais-amjed commented
@Amrit131 , So after you are done making the changes mentioned in the Code Review, you should ask for another Code Review from your dashboard and someone will review your PR. 
Also you should not close or delete this branch or PR and after making the required changes in this branch, you should ask for another Code Review using this Same Pull Request as you did before.
This way the next code reviewer will have an idea of my Code Review and they will be able to check your code accordingly.
All of this should be mentioned in the Code Review process at the bottom of your project requirements.

2022-09-21 07:47 UTC, Amrit131 commented
@awais-amjed, Thank you for helping me out, I will make sure to follow the instructions. Also about closing the pull request/branch it was a mistake from my side, in panic I got confused a little bit and closed the PR/branch while trying to do something else. I will make sure it never happens again.
Thank you.

2022-09-21 07:54 UTC, sumairq approved these changes
### Hi @Amrit131 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 08:02 UTC, Amrit131 commented
Thank you! Sumair.

On Wed, Sep 21, 2022 at 1:24 PM Sumair Qaisar ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hi @Amrit131 <https://github.com/Amrit131> ,
>
>
> <https://camo.githubusercontent.com/d8de195a08af080c4ae2fd36bfcf741de68f66af2162d291a21e113ce1b490fc/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
> ✔️ Good commit history
> ✔️Linters are passing
> ✔️Very professional README
> ✔️Correct Github flow
> ✔️Descriptive PR
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Amrit131/hello-microverse/pull/1#pullrequestreview-1114936907>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU4JI5CKDEB4DTKURA6IUBTV7K5MFANCNFSM6AAAAAAQRGQIFU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-21 08:03 UTC, merged